apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: setup
manifests:
  rawYaml:
    - extras/jwt/jwt-secret.yaml
    - dev-kubernetes-manifests/config.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: db
requires:
  - configs:
      - setup
build:
  artifacts:
    - image: gcr.io/bank-of-anthos-ci/accounts-db
      context: src/accounts-db
    - image: gcr.io/bank-of-anthos-ci/ledger-db
      context: src/ledger-db
manifests:
  rawYaml:
    - dev-kubernetes-manifests/accounts-db.yaml
    - dev-kubernetes-manifests/ledger-db.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: backend
requires:
  - configs:
      - db
build:
  artifacts:
    - image: gcr.io/bank-of-anthos-ci/ledgerwriter
      jib:
        project: src/ledgerwriter
    - image: gcr.io/bank-of-anthos-ci/balancereader
      jib:
        project: src/balancereader
    - image: gcr.io/bank-of-anthos-ci/transactionhistory
      jib:
        project: src/transactionhistory
    - image: gcr.io/bank-of-anthos-ci/contacts
      context: src/contacts
    - image: gcr.io/bank-of-anthos-ci/userservice
      context: src/userservice
manifests:
  rawYaml:
    - dev-kubernetes-manifests/balance-reader.yaml
    - dev-kubernetes-manifests/contacts.yaml
    - dev-kubernetes-manifests/ledger-writer.yaml
    - dev-kubernetes-manifests/transaction-history.yaml
    - dev-kubernetes-manifests/userservice.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: gcr.io/bank-of-anthos-ci/frontend
      context: src/frontend
manifests:
  rawYaml:
    - dev-kubernetes-manifests/frontend.yaml
    - dev-kubernetes-manifests/redis.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: loadgenerator
build:
  artifacts:
    - image: gcr.io/bank-of-anthos-ci/loadgenerator
      context: src/loadgenerator
manifests:
  rawYaml:
    - dev-kubernetes-manifests/loadgenerator.yaml
deploy:
  kubectl: {}
